---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: debian-7.2.0
    driver_config:
      customize:
        memory: 2048
        cpus: 1
      synced_folders:
        - ["C:/software", "/software"]
  - name: oel-7.0
    driver_config:
      box: OEL-7.0_BS-x86_64
      customize:
        memory: 2048
        cpus: 1
      synced_folders:
        - ["C:/software", "/software"]
  - name: oel-6.6
    driver_config:
      box: OEL-6.6
      customize:
        memory: 2048
        cpus: 1
      synced_folders:
        - ["C:/software", "/software"]
  - name: oel-5.8
    driver_config:
      box: OEL-5.8
      customize:
        memory: 2048
        cpus: 1
      synced_folders:
        - ["C:/software", "/software"]
  - name: windows-2012r2
    transport:
      name: winrm
    driver_config:
      box: win2012r2
      customize:
        memory: 4572
        cpus: 2
      synced_folders:
        - ["C:/software", "/software"]
  - name: windows-8.1
    transport:
      name: winrm
    driver_config:
      box: win81x64
      customize:
        memory: 4572
        cpus: 2
      synced_folders:
        - ["C:/software", "/software"]

suites:
  - name: wls1036
    run_list:
      - recipe[fmw_jdk::install]
      - recipe[fmw_jdk::rng_service]
      - recipe[fmw_wls::setup]
      - recipe[fmw_wls::install]
      - recipe[fmw_bsu::weblogic]
    attributes:
      fmw:
        java_home_dir:       "/usr/java/jdk1.7.0_75"
        middleware_home_dir: "/opt/oracle/middleware_1036"
        version:             "10.3.6"
      fmw_jdk:
        source_file:         "/software/jdk-7u75-linux-x64.tar.gz"
      fmw_wls:
        source_file:         "/software/wls1036_generic.jar"
      fmw_bsu:
        patch_id:            "YUIS"
        source_file:         "/software/p20181997_1036_Generic.zip"
    excludes:
      - windows-2012r2
      - windows-8.1
  - name: wls1036_win
    run_list:
      - recipe[fmw_jdk::install]
      - recipe[fmw_wls::install]
      - recipe[fmw_bsu::weblogic]
    attributes:
      fmw:
        java_home_dir:           "c:\\java\\jdk1.7.0_75"
        middleware_home_dir:     "c:\\oracle\\middleware_1036"
        version:                 "10.3.6"
        tmp_dir:                 "C:\\Users\\vagrant\\AppData\\Local\\temp"
      fmw_jdk:
        source_file:             "c:\\software\\jdk-7u75-windows-x64.exe"
      fmw_wls:
        source_file:             "c:\\software\\wls1036_generic.jar"
      fmw_bsu:
        patch_id:                "YUIS"
        source_file:             "c:\\software\\p20181997_1036_Generic.zip"
    excludes:
      - debian-7.2.0
      - oel-7.0
      - oel-6.6
      - oel-5.8