---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: debian-7.2.0
    driver_config:
      customize:
        memory: 2048
        cpus: 1
      synced_folders:
        - ["C:/software", "/software"]
  - name: oel-7.0
    driver_config:
      box: OEL-7.0_BS-x86_64
      customize:
        memory: 2048
        cpus: 1
      synced_folders:
        - ["C:/software", "/software"]
  - name: oel-6.6
    driver_config:
      box: OEL-6.6
      customize:
        memory: 2048
        cpus: 1
      synced_folders:
        - ["C:/software", "/software"]
  - name: oel-5.8
    driver_config:
      box: OEL-5.8
      customize:
        memory: 2048
        cpus: 1
      synced_folders:
        - ["C:/software", "/software"]
  - name: windows-2012r2
    transport:
      name: winrm
    driver_config:
      box: win2012r2
      customize:
        memory: 4572
        cpus: 2
      synced_folders:
        - ["C:/software", "/software"]
  - name: windows-8.1
    transport:
      name: winrm
    driver_config:
      box: win81x64
      customize:
        memory: 4572
        cpus: 2
      synced_folders:
        - ["C:/software", "/software"]
  - name: solaris-10
    driver_config:
      box: solaris10-x86_64
      customize:
        memory: 2048
        cpus: 1
      synced_folders:
        - ["C:/software", "/software"]

suites:
  - name: wls1213
    run_list:
      - recipe[fmw_jdk::install]
      - recipe[fmw_jdk::rng_service]
      - recipe[fmw_wls::setup]
      - recipe[fmw_wls::install]
      - recipe[fmw_inst::soa_suite]
      - recipe[fmw_opatch::weblogic]
      - recipe[fmw_opatch::soa_suite]
    attributes:
      fmw:
        java_home_dir:           "/usr/java/jdk1.7.0_75"
        middleware_home_dir:     "/opt/oracle/middleware_1213"
        version:                 "12.1.3"
      fmw_jdk:
        source_file:             "/software/jdk-7u75-linux-x64.tar.gz"
      fmw_wls:
        source_file:             "/software/fmw_12.1.3.0.0_infrastructure.jar"
        install_type:            "infra"
      fmw_inst:
        soa_suite_source_file:   "/software/fmw_12.1.3.0.0_soa_Disk1_1of1.zip"
      fmw_opatch:
        weblogic_patch_id:       "20838345"
        weblogic_source_file:    "/software/p20838345_121300_Generic.zip"
        soa_suite_patch_id:      "20423408"
        soa_suite_source_file:   "/software/p20423408_121300_Generic.zip"
    excludes:
      - windows-2012r2
      - windows-8.1
      - solaris-10
  - name: wls1213_sol
    run_list:
      - recipe[fmw_jdk::install]
      - recipe[fmw_wls::setup]
      - recipe[fmw_wls::install]
      - recipe[fmw_inst::soa_suite]
      - recipe[fmw_opatch::weblogic]
      - recipe[fmw_opatch::soa_suite]
    attributes:
      fmw:
        java_home_dir:           "/usr/jdk/instances/jdk1.7.0_75"
        middleware_home_dir:     "/opt/oracle/middleware_1213"
        version:                 "12.1.3"
      fmw_jdk:
        source_file:             "/software/jdk-7u75-solaris-i586.tar.gz"
        source_x64_file:         "/software/jdk-7u75-solaris-x64.tar.gz"
      fmw_wls:
        source_file:             "/software/fmw_12.1.3.0.0_infrastructure.jar"
        install_type:            "infra"
      fmw_inst:
        soa_suite_source_file:   "/software/fmw_12.1.3.0.0_soa_Disk1_1of1.zip"
      fmw_opatch:
        weblogic_patch_id:       "20838345"
        weblogic_source_file:    "/software/p20838345_121300_Generic.zip"
        soa_suite_patch_id:      "20423408"
        soa_suite_source_file:   "/software/p20423408_121300_Generic.zip"
    excludes:
      - windows-2012r2
      - windows-8.1
      - debian-7.2.0
      - oel-7.0
      - oel-6.6
      - oel-5.8
  - name: wls1213_win
    run_list:
      - recipe[fmw_jdk::install]
      - recipe[fmw_wls::install]
      - recipe[fmw_inst::soa_suite]
      - recipe[fmw_opatch::weblogic]
      - recipe[fmw_opatch::soa_suite]
    attributes:
      fmw:
        java_home_dir:           "c:\\java\\jdk1.7.0_75"
        middleware_home_dir:     "c:\\oracle\\middleware_1213"
        version:                 "12.1.3"
        tmp_dir:                 "C:\\Users\\vagrant\\AppData\\Local\\temp"
      fmw_jdk:
        source_file:             "c:\\software\\jdk-7u75-windows-x64.exe"
      fmw_wls:
        source_file:             "c:\\software\\fmw_12.1.3.0.0_infrastructure.jar"
        install_type:            "infra"
      fmw_inst:
        soa_suite_source_file:   "c:\\software\\fmw_12.1.3.0.0_soa_Disk1_1of1.zip"
        soa_suite_install_type:  "BPM"
      fmw_opatch:
        weblogic_patch_id:       "20838345"
        weblogic_source_file:    "c:\\software\\p20838345_121300_Generic.zip"
        soa_suite_patch_id:      "20423408"
        soa_suite_source_file:   "c:\\software\\p20423408_121300_Generic.zip"
    excludes:
      - debian-7.2.0
      - oel-7.0
      - oel-6.6
      - oel-5.8
      - solaris-10
  - name: wls1036
    run_list:
      - recipe[fmw_jdk::install]
      - recipe[fmw_jdk::rng_service]
      - recipe[fmw_wls::setup]
      - recipe[fmw_wls::install]
      - recipe[fmw_inst::soa_suite]
      - recipe[fmw_inst::service_bus]
      - recipe[fmw_opatch::service_bus]
      - recipe[fmw_opatch::soa_suite]
    attributes:
      fmw:
        java_home_dir:           "/usr/java/jdk1.7.0_75"
        middleware_home_dir:     "/opt/oracle/middleware_1036"
        version:                 "10.3.6"
      fmw_jdk:
        source_file:             "/software/jdk-7u75-linux-x64.tar.gz"
      fmw_wls:
        source_file:             "/software/wls1036_generic.jar"
      fmw_inst:
        soa_suite_source_file:   "/software/ofm_soa_generic_11.1.1.7.0_disk1_1of2.zip"
        soa_suite_source_2_file: "/software/ofm_soa_generic_11.1.1.7.0_disk1_2of2.zip"
        service_bus_source_file: "/software/ofm_osb_generic_11.1.1.7.0_disk1_1of1.zip"
      fmw_opatch:
        soa_suite_patch_id:      "20423535"
        soa_suite_source_file:   "/software/p20423535_111170_Generic.zip"
        service_bus_patch_id:    "20423630"
        service_bus_source_file: "/software/p20423630_111170_Generic.zip"
    excludes:
      - windows-2012r2
      - windows-8.1
      - solaris-10
  - name: wls1036_sol
    run_list:
      - recipe[fmw_jdk::install]
      - recipe[fmw_wls::setup]
      - recipe[fmw_wls::install]
      - recipe[fmw_inst::soa_suite]
      - recipe[fmw_inst::service_bus]
      - recipe[fmw_opatch::service_bus]
      - recipe[fmw_opatch::soa_suite]
    attributes:
      fmw:
        java_home_dir:           "/usr/jdk/instances/jdk1.7.0_75"
        middleware_home_dir:     "/opt/oracle/middleware_1036"
        version:                 "10.3.6"
      fmw_jdk:
        source_file:             "/software/jdk-7u75-solaris-i586.tar.gz"
        source_x64_file:         "/software/jdk-7u75-solaris-x64.tar.gz"
      fmw_wls:
        source_file:             "/software/wls1036_generic.jar"
      fmw_inst:
        soa_suite_source_file:   "/software/ofm_soa_generic_11.1.1.7.0_disk1_1of2.zip"
        soa_suite_source_2_file: "/software/ofm_soa_generic_11.1.1.7.0_disk1_2of2.zip"
        service_bus_source_file: "/software/ofm_osb_generic_11.1.1.7.0_disk1_1of1.zip"
      fmw_opatch:
        soa_suite_patch_id:      "20423535"
        soa_suite_source_file:   "/software/p20423535_111170_Generic.zip"
        service_bus_patch_id:    "20423630"
        service_bus_source_file: "/software/p20423630_111170_Generic.zip"
    excludes:
      - windows-2012r2
      - windows-8.1
      - debian-7.2.0
      - oel-7.0
      - oel-6.6
      - oel-5.8
  - name: wls1036_win
    run_list:
      - recipe[fmw_jdk::install]
      - recipe[fmw_wls::install]
      - recipe[fmw_inst::soa_suite]
      - recipe[fmw_inst::service_bus]
      - recipe[fmw_opatch::service_bus]
      - recipe[fmw_opatch::soa_suite]
    attributes:
      fmw:
        java_home_dir:           "c:\\java\\jdk1.7.0_75"
        middleware_home_dir:     "c:\\oracle\\middleware_1036"
        version:                 "10.3.6"
        tmp_dir:                 "C:\\Users\\vagrant\\AppData\\Local\\temp"
      fmw_jdk:
        source_file:             "c:\\software\\jdk-7u75-windows-x64.exe"
      fmw_wls:
        source_file:             "c:\\software\\wls1036_generic.jar"
      fmw_inst:
        soa_suite_source_file:   "c:\\software\\ofm_soa_generic_11.1.1.7.0_disk1_1of2.zip"
        soa_suite_source_2_file: "c:\\software\\ofm_soa_generic_11.1.1.7.0_disk1_2of2.zip"
        service_bus_source_file: "c:\\software\\ofm_osb_generic_11.1.1.7.0_disk1_1of1.zip"
      fmw_opatch:
        soa_suite_patch_id:      "20423535"
        soa_suite_source_file:   "c:\\software\\p20423535_111170_Generic.zip"
        service_bus_patch_id:    "20423630"
        service_bus_source_file: "c:\\software\\p20423630_111170_Generic.zip"
    excludes:
      - debian-7.2.0
      - oel-7.0
      - oel-6.6
      - oel-5.8
      - solaris-10